modLoader="javafml" #mandatory
loaderVersion="${forge_loader_version_range}"
license="CC-BY-NC-4.0"
issueTrackerURL="https://github.com/${github}/issues"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://github.com/${github}" #optional
logoFile="icon.png" #optional
credits="${credits}" #optional
authors="${mod_author}" #optional
description='''${mod_description}'''
[[dependencies.arsenal]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forge_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.arsenal]]
   modId="minecraft"
   mandatory=true
   versionRange="[${minecraft_version},)"
   ordering="NONE"
   side="BOTH"
[[dependencies.arsenal]]
   modId="miapi"
   mandatory=true
   versionRange="[${miapi_version},)"
   ordering="NONE"
   side="BOTH"
